### ISSUE TITLE
Regex check to enforce branch names should apply when pushing new branch only

### ISSUE THREAD

**Issue by ryandb** [tomasbjerre/simple-stash-commit-checker#42]
If there are no commits in push request, the Regex will not be tested, allowing the new (non-compliant) branch to be created.

To reproduce:  set  "Check branch name"  to a valid RegEx, something like:   
```
/^feature\/.+$/
```
create a non-compliant branch name and push:
```
git checkout -b bad_branch_name
git push
```

This branch is still accepted in the Stash repo, although subsequent commits to that branch will not be accepted.

However, a command to get rid of an existing branch should not fail due to this condition (but still may fail based of other hooks or conditions. )

```git push origin  :branch_to_delete```        <---- this should work, regardless of the regex for "Check branch name"

**Comment by tomasbjerre** [comment]
Released in 1.12, open issue again if problem still exists.

**Comment by ryandb** [comment]
Nice plug-in.   Thanks for the quick turn.
